FROM node:20.12.2

RUN npm install -g json-server@0.17.4

WORKDIR /data
COPY "src/db.json" .

#EXPOSE 80
#ADD run.sh /run.sh
#ENTRYPOINT ["bash", "/run.sh"]
#CMD []
ENTRYPOINT ["json-server", "--port", "8080", "--host", "0.0.0.0"]

CMD ["/data/db.json"]
